import Link from 'next/link';
import Navbar from '../components/Navbar';
import results from './results.json';

export const metadata = { title: 'Measured progress — TokenShrink', description: 'Experimental compression measurements, limitations, and the TokenShrink research roadmap.' };
const number = value => value.toLocaleString('en-US');
export default function ProgressPage() {
  const repeated = results.results.find(row => row.encoding === 'cl100k' && row.fixture === 'repeated_handoff');
  return <><Navbar /><main className="pt-32 pb-20 px-6 max-w-5xl mx-auto space-y-12">
    <section><p className="text-savings text-sm">Research log · {results.date}</p><h1 className="text-4xl font-bold mt-3">Smaller context. Measured progress.</h1><p className="text-text-secondary mt-4 max-w-3xl">We are testing whether a shared dictionary can reduce repeated conversation context. We publish the overhead and the cases where compression does not help.</p><p className="mt-4 text-sm">Looking for your own usage? <Link href="/dashboard" className="text-savings underline">Open your dashboard</Link>. Project owners can see recorded successful compressions in <Link href="/dashboard/operations" className="text-savings underline">Operations</Link>.</p></section>
    <section className="border border-border bg-bg-card rounded-xl p-6"><h2 className="text-2xl font-semibold">Aster-1 · experimental dictionary codec</h2><p className="mt-3 text-text-secondary">Repeated text becomes a short reference with a complete decoder. The software decoder restored every tested input exactly. This does not establish that an AI model will answer identically.</p><p className="mt-3 text-text-secondary">This experiment is separate from the current hosted compressor and npm release. The current compressor uses heuristics; test its results against your task requirements.</p></section>
    <section><h2 className="text-2xl font-semibold">First benchmark</h2><p className="mt-3 mb-5 text-text-secondary">Synthetic fixtures, measured locally using gpt-tokenizer 3.4.0. Each turn includes the growing input history, decoder, dictionary, escaping, and JSON. Repeated handoffs deliberately favor dictionary compression. These are not customer savings, provider bills, or a forecast.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Aster-1 cumulative synthetic input token comparison</caption><thead><tr className="border-b border-border"><th className="p-3">Fixture</th><th className="p-3">Encoding</th><th className="p-3">Original tokens</th><th className="p-3">With codec</th><th className="p-3">Reduction</th></tr></thead><tbody>{results.results.map(row => <tr key={row.encoding+row.fixture} className="border-b border-border"><th scope="row" className="p-3 font-normal">{row.fixture.replaceAll('_', ' ')} · {row.turnCount} turns</th><td className="p-3">{row.encoding}</td><td className="p-3">{number(row.totalOriginal)}</td><td className="p-3">{number(row.totalOutput)}</td><td className="p-3 text-savings">{row.savingsPercent}%</td></tr>)}</tbody></table></div><p className="mt-4 text-sm text-text-muted">Excludes provider role framing, tool schemas, outputs, retries, latency, and cache pricing. These encodings do not establish token counts for Claude, MiMo, MiniMax, or Gemini. Model answer equivalence has not been established.</p></section>
    <section><h2 className="text-2xl font-semibold">When does the dictionary pay off?</h2><p className="mt-3 text-text-secondary">In the repeated-handoff fixture, turn 3 is the first profitable turn. Early inputs stay unchanged. Each bar below counts the full input for that individual turn, including the decoder again.</p><div className="mt-6 space-y-5">{repeated.turns.map(turn => <div key={turn.turn}><p className="text-sm mb-2">Turn {turn.turn}: {number(turn.originalTokens)} → {number(turn.outputTokens)} tokens{!turn.applied ? ' · unchanged' : ''}</p><div className="h-3 bg-border rounded overflow-hidden" role="img" aria-label={`${Math.round(100*turn.outputTokens/turn.originalTokens)} percent of original tokens retained`}><div className="bg-savings h-full rounded" style={{width:`${100*turn.outputTokens/turn.originalTokens}%`}} /></div></div>)}</div></section>
    <section><h2 className="text-2xl font-semibold">Live model smoke test · MiMo</h2><p className="mt-3 text-text-secondary">One synthetic development handoff, tested twice with mimo-v2.5: original input 715 tokens, encoded input 394 tokens, with 44 output tokens in each response. The model returned the same correct project facts, including a “do not publish” restriction, but wrapped both answers in Markdown. Both therefore failed the requested strict JSON format check.</p><p className="mt-3 text-sm text-text-muted">This small test does not establish general answer equivalence. Cached tokens were present in the repeat; token reduction is not a measured bill reduction. No hidden assistant instructions or tools were compressed.</p></section>
    <section><h2 className="text-2xl font-semibold">Next generations</h2><dl className="mt-5 space-y-5"><div><dt className="font-semibold">Aster-1 — literal dictionary · local prototype</dt><dd className="text-text-secondary mt-1">Exact software round trips, full payload accounting, and a bypass when overhead is larger than the saving.</dd></div><div><dt className="font-semibold">Lyra-2 — model evaluation · proposed</dt><dd className="text-text-secondary mt-1">Compare original and encoded prompts on held-out tasks. Count correct answers, failures, input and output tokens, retries, and latency.</dd></div><div><dt className="font-semibold">Orion-3 — session integration · proposed</dt><dd className="text-text-secondary mt-1">Preserve roles and tool boundaries, validate dictionary versions, and compare compression with provider caching. No launch date or savings target is promised.</dd></div></dl><p className="mt-5 text-sm text-text-muted">Names identify research milestones, not new foundation models. A generation advances only with reviewable evidence.</p></section>
    <section><h2 className="text-2xl font-semibold">Help choose the next test</h2><p className="mt-3 text-text-secondary">Tell us which repeated workflows cost you tokens. Share a synthetic example without private data or credentials.</p><Link href="/feedback" className="inline-block mt-4 rounded bg-savings text-bg px-5 py-3">Send feedback</Link></section>
  </main></>;
}
